---
kubernetes_cni:
  plugin: calico
  calico:
    manifest_url: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml"
    calicoctl_url: "https://github.com/projectcalico/calicoctl/releases/download/v1.6.1/calicoctl"
  flannel:
    manifest_url: "https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml"
