---
apiVersion: v1
kind: Pod
metadata:
  name: kube-ucarp-vip
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-ucarp-vip
    image: ctracey/ucarp
    securityContext:
      privileged: true
    env:
    - name: UCARP_VID
      value: "41"
    - name: UCARP_ADDRESS
      value: "10.10.10.3/25"
    - name: UCARP_PASSWORD
      value: "mypassword"
    - name: UCARP_DEVICE
      value: "eth0``"
