---
- name: add docker dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: add docker repo
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable/
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true

- name: determine if docker binary is present (implies Docker is installed)
  stat:
    path: /usr/bin/docker
  register: docker_present

- name: install Docker CE if docker binary is not present
  command: "yum install -y --setopt=obsoletes=0 docker-ce-selinux-{{docker_redhat_version}} docker-ce-{{docker_redhat_version}}"
  when: docker_present.stat.exists == False

#- name: install docker
#  yum:
#    name: "{{ item }}"
#    state: present
#    allow_downgrade: True
#  with_items:
#    - "docker-ce-selinux-{{docker_redhat_version}}"

- name: start docker service
  service:
    name: docker
    enabled: true
    state: started
